# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb23c377ae0210fde50b57bcaf55b339e791c0d024a14c930fc16b5f2b73238068a347d1c85d9381fb76da6d7be1548b8d1bd4f4e63bfde2994377cbc545e0e

test:
  secret_key_base: a4cd253974874c99e9b2f7b9272cbb3b7442a77a229ba31005d7a1fe927fdcb22156bf6780329e950aa41b6a05891eaa137b5135c8e314c89b7649f26c783070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
